spring.config.activate.on-profile=prod

spring.jpa.hibernate.ddl-auto=validate

logging.level.root=INFO
logging.level.com.authentication.server=INFO

# Disable OpenAPI/Swagger UI in prod by default.
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

