spring.config.activate.on-profile=dev

# Supabase requires SSL. Prefer including '?sslmode=require' in SUPABASE_DB_URL.
# spring.datasource.url=${SUPABASE_DB_URL}?sslmode=require

spring.jpa.hibernate.ddl-auto=update
